FROM ubuntu:22.04
RUN apt-get update && apt-get -y install git curl dos2unix
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN pip3 install torch numpy pandas
RUN pip3 install ipykernel
RUN pip3 install jupyterlab ipynb
RUN pip3 install matplotlib
RUN pip3 install ipympl
RUN pip3 install mpl_interactions
